### ISSUE TITLE
按住列表不放一直滚动吸附悬停功能消失

### ISSUE THREAD

**Issue by loganguo** [sfsheng0322/StickyHeaderListView#12]
小米手机上正常，但是在华为手机GRA-UL10 (EMUI 3.1)上不正常

**Comment by loganguo** [comment]
![image](https://cloud.githubusercontent.com/assets/9315399/17286967/6a2caf5c-57ff-11e6-9ce0-4d042f44a67b.png)

**Comment by sfsheng0322** [comment]
你得再改改吸附的逻辑，实际开发中我也遇到了

**Comment by loganguo** [comment]
问题已经解决了，删掉了一行

![image](https://cloud.githubusercontent.com/assets/9315399/17318960/f259c01e-58bc-11e6-9b7c-adf6410430fb.png)
