### ISSUE TITLE
加载图片失败

### ISSUE THREAD

**Issue by singsoul** [sfsheng0322/StickyHeaderListView#14]
你好，我在项目中借鉴了一下你的这个功能，我发现了一个问题，首页设计的时候会出现多种样式的列表，用您的这个功能能完美实现，但是加载图片的时候会出现一个问题就是，图片加载失败，这个问题我也搞不清是为什么，后台传回的uri地址是正确的，但是加载的时候就错误了

**Comment by sfsheng0322** [comment]
你把 uri 提供一下，我看看问题是不是出在 GlideImageView
