### ISSUE TITLE
求助  在Fragment中使用出现空指针 

### ISSUE THREAD

**Issue by cnmao** [sfsheng0322/StickyHeaderListView#16]
在Activity中我使用正常 
但是在 V4 的 Fragment中  出现空指针  
出现在 HeaderBannerView 类 的 
    AbsListView.LayoutParams layoutParams = (AbsListView.LayoutParams) rlBanner.getLayoutParams();
        layoutParams.height = bannerHeight; // 显示的是这个地方的 layoutParams 为 null 
        rlBanner.setLayoutParams(layoutParams);

**Comment by sfsheng0322** [comment]
rlBanner 是不是没有添加进布局里面呢
如果为空可以new AbsListView.LayoutParams

**Comment by cnmao** [comment]
谢谢 整理好了 。

**Comment by sfsheng0322** [comment]
:)
