### ISSUE TITLE
快速滚动，头部颜色渐变失效

### ISSUE THREAD

**Issue by mattxzhang** [sfsheng0322/StickyHeaderListView#4]
快速滚动的时候，头部还是透明
![screenshot_2016-04-28-11-04-44](https://cloud.githubusercontent.com/assets/8435870/14874289/27fb85f4-0d31-11e6-8106-ff082844ce34.png)

**Comment by sfsheng0322** [comment]
问题已经解决啦，请下载最新apk和查看最新代码
