### ISSUE TITLE
请问能把listview改成PulltoRefreshListView吗？

### ISSUE THREAD

**Issue by Logan676** [sfsheng0322/StickyHeaderListView#6]
很赞的项目，已经用在了我们的项目中，可是由于我们项目中的其它页面全部是PulltoRefreshListView的刷新效果，为了保持效果一致，这个demo中的listview也需要改成那种效果。大神，不知道这是否可行呢，可行的话能否简单说下实现思路呢？

**Comment by sfsheng0322** [comment]
可以改啊！完全没有问题！相信你。改去吧。

**Comment by Logan676** [comment]
SmoothListView继承自listview，添加多个头部时，调用的是`listView.addHeaderView(view);`这个方法。请问我使用`pullToRefreshListView.getRefreshView().addHeaderView(view)`为什么得不到同样的效果呢？现在错误的效果是前面的头部都会被最后一个头部覆盖。
